"""webui-service 测试：配置视图/安全写入/切源动作/lx 校验回路/反代与二维码。

supervisorctl 与音源 HTTP 均离线：前者 monkeypatch，后者 MockTransport。
"""
from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import httpx
import pytest
from fastapi.testclient import TestClient

HERE = Path(__file__).resolve().parent


def _load_webui():
    spec = importlib.util.spec_from_file_location("webui_service_app", HERE / "app.py")
    mod = importlib.util.module_from_spec(spec)
    sys.modules["webui_service_app"] = mod
    spec.loader.exec_module(mod)
    return mod


webui = _load_webui()

BASE_ENV = """# generated by install.sh — do not commit
FNMUSIC_NETEASE_ENABLED='true'
FNMUSIC_MUSICDL_ENABLED='false'
FNMUSIC_LX_ENABLED='false'
FNMUSIC_ONLINE_SOURCES='KuwoMusicClient'
MUSICDL_SOURCES='KuwoMusicClient'
LX_SOURCE_URL=''
FNMUSIC_QUALITY_MODE='high'
FNMUSIC_RECOMMEND_HOT='true'
FNMUSIC_RECOMMEND_DAILY='true'
FNMUSIC_TEE_SAVE_ENABLED='true'
FNMUSIC_TEE_CACHE_MAX='2'
CUSTOM_KEY='keepme'
"""


@pytest.fixture
def env_file(tmp_path, monkeypatch):
    env = tmp_path / ".env"
    env.write_text(BASE_ENV, encoding="utf-8")
    (tmp_path / "VERSION").write_text("2.0.0\n", encoding="utf-8")
    monkeypatch.setattr(webui, "ENV_PATH", env)
    monkeypatch.setattr(webui, "VERSION_PATH", tmp_path / "VERSION")
    return env


@pytest.fixture
def svctl(monkeypatch):
    calls: list[tuple] = []
    status_output = {
        "musicdl": "musicdl                        STOPPED   Not started",
        "musicbox": "musicbox                       RUNNING   pid 7, uptime 0:01:00",
        "lxmusic": "lxmusic                        STOPPED   Not started",
        "webui": "webui                          RUNNING   pid 8, uptime 0:01:00",
    }

    def fake(*args, timeout=20.0):
        calls.append(tuple(args))
        if args[0] == "status":
            # 真实 supervisorctl：存在 STOPPED 程序时退出码为 3（按需加载的常态）
            return 3, "\n".join(status_output.values())
        return 0, f"{args[0]}ed {args[1]}"

    monkeypatch.setattr(webui, "supervisorctl", fake)
    fake.calls = calls
    return fake


def _mock_http(handler):
    webui.app.state.http = httpx.AsyncClient(transport=httpx.MockTransport(handler))


# ------------------------------------------------------------------ 配置视图 ---

def test_config_view_merges_defaults(env_file):
    with TestClient(webui.app) as client:
        r = client.get("/api/config")
        assert r.status_code == 200
        rj = r.json()
        assert rj["values"]["FNMUSIC_NETEASE_ENABLED"] == "true"
        assert rj["values"]["LX_SOURCE_URL"] == ""
        assert rj["values"]["FNMUSIC_LLM_MODEL"] == "gpt-4o-mini"  # 缺省补齐
        assert "CUSTOM_KEY" not in rj["values"]  # 非管理键不进视图
        assert rj["schema"]["FNMUSIC_QUALITY_MODE"]["values"] == ["high", "balanced", "smooth"]


# ------------------------------------------------------------------ PUT 校验 ---

def test_put_rejects_unknown_key(env_file):
    with TestClient(webui.app) as client:
        r = client.put("/api/config", json={"values": {"NOT_A_KEY": "1"}})
        assert r.status_code == 400
        assert "不支持的配置键" in r.json()["error"]


def test_put_rejects_bad_enum(env_file):
    with TestClient(webui.app) as client:
        r = client.put("/api/config", json={"values": {"FNMUSIC_QUALITY_MODE": "ultra"}})
        assert r.status_code == 400


def test_put_rejects_multi_provider(env_file):
    with TestClient(webui.app) as client:
        r = client.put("/api/config", json={"values": {"FNMUSIC_LX_ENABLED": "true"}})
        assert r.status_code == 400
        assert "三选一" in r.json()["error"]


def test_put_rejects_zero_provider(env_file):
    with TestClient(webui.app) as client:
        r = client.put("/api/config", json={"values": {"FNMUSIC_NETEASE_ENABLED": "false"}})
        assert r.status_code == 400
        assert "至少" in r.json()["error"]


# ------------------------------------------------------------------ 写入语义 ---

def test_put_hot_keys_roundtrip_preserves_custom(env_file):
    with TestClient(webui.app) as client:
        r = client.put("/api/config", json={"values": {
            "FNMUSIC_QUALITY_MODE": "balanced",
            "FNMUSIC_RECOMMEND_DAILY": False,
            "FNMUSIC_TEE_CACHE_MAX": 5,
        }})
        assert r.status_code == 200
        rj = r.json()
        assert set(rj["changed"]) == {"FNMUSIC_QUALITY_MODE", "FNMUSIC_RECOMMEND_DAILY", "FNMUSIC_TEE_CACHE_MAX"}
        assert rj["actions"] == []
    text = env_file.read_text(encoding="utf-8")
    assert "FNMUSIC_QUALITY_MODE='balanced'" in text
    assert "FNMUSIC_TEE_CACHE_MAX='5'" in text
    assert "CUSTOM_KEY='keepme'" in text          # 用户自定义键保留
    assert "# generated by install.sh" in text     # 文件头保留
    assert env_file.with_suffix(".env.webui.bak").exists()  # 写前备份


def test_put_noop_returns_empty_change(env_file):
    with TestClient(webui.app) as client:
        r = client.put("/api/config", json={"values": {"FNMUSIC_QUALITY_MODE": "high"}})
        assert r.status_code == 200
        assert r.json()["changed"] == []


def test_put_int_clamps_and_bool_normalizes(env_file):
    with TestClient(webui.app) as client:
        r = client.put("/api/config", json={"values": {"FNMUSIC_TEE_CACHE_MAX": 999}})
        assert r.status_code == 200
    assert "FNMUSIC_TEE_CACHE_MAX='100'" in env_file.read_text(encoding="utf-8")


# ------------------------------------------------------------------ 切源动作 ---

def test_provider_switch_stops_old_starts_new(env_file, svctl):
    with TestClient(webui.app) as client:
        r = client.put("/api/config", json={"values": {
            "FNMUSIC_NETEASE_ENABLED": "false",
            "FNMUSIC_LX_ENABLED": "true",
        }})
        assert r.status_code == 200
        actions = r.json()["actions"]
        assert ("stop", "musicbox") in svctl.calls
        assert ("start", "lxmusic") in svctl.calls
        assert all(a["ok"] for a in actions if a["kind"] == "process")


def test_musicdl_platform_change_restarts_process(env_file, svctl):
    # 先切到 musicdl
    with TestClient(webui.app) as client:
        r = client.put("/api/config", json={"values": {
            "FNMUSIC_NETEASE_ENABLED": "false",
            "FNMUSIC_MUSICDL_ENABLED": "true",
            "FNMUSIC_ONLINE_SOURCES": "KuwoMusicClient,MiguMusicClient",
        }})
        assert r.status_code == 200
        svctl.calls.clear()
        # 平台再次变更（provider 不变）→ restart musicdl
        r2 = client.put("/api/config", json={"values": {
            "FNMUSIC_ONLINE_SOURCES": "KuwoMusicClient",
        }})
        assert r2.status_code == 200
        assert ("restart", "musicdl") in svctl.calls
    text = env_file.read_text(encoding="utf-8")
    assert "MUSICDL_SOURCES='KuwoMusicClient'" in text or "MUSICDL_SOURCES" in text


# ------------------------------------------------------------------ lx 换源回路 ---

def test_lx_url_change_verifies_activates_and_derives_sources(env_file, svctl, monkeypatch):
    monkeypatch.setitem(webui.CONF, "lx_url", "http://lx.test")
    hits = {"verify": 0, "activate": 0}

    def handler(request: httpx.Request) -> httpx.Response:
        url = str(request.url)
        if url.endswith("/api/v1/source/verify"):
            hits["verify"] += 1
            assert request.read()  # 携带 body
            return httpx.Response(200, json={"ok": True, "data": {
                "platforms": ["kw", "kg"], "meta": {"name": "t"}, "probe": {"title": "x"},
            }})
        if request.url.host == "lx.test" and request.method == "POST":
            hits["activate"] += 1
            return httpx.Response(200, json={"ok": True, "data": {"url": "https://s/1.js"}})
        return httpx.Response(200, json={"ok": True})

    _mock_http(handler)

    # 切到 lx 并换 URL：verify → 写 env（含推导 LX_SOURCES）→ 起进程 → 激活
    with TestClient(webui.app) as client:
        r = client.put("/api/config", json={"values": {
            "FNMUSIC_NETEASE_ENABLED": "false",
            "FNMUSIC_LX_ENABLED": "true",
            "LX_SOURCE_URL": "https://s/1.js",
        }})
        assert r.status_code == 200
    assert hits["verify"] == 1
    assert hits["activate"] == 1
    text = env_file.read_text(encoding="utf-8")
    assert "LX_SOURCE_URL='https://s/1.js'" in text
    assert "LX_SOURCES='kw,kg'" in text  # 来自校验报告的可用平台


def test_lx_url_change_blocked_when_verify_fails(env_file, svctl, monkeypatch):
    monkeypatch.setitem(webui.CONF, "lx_url", "http://lx.test")

    def handler(request: httpx.Request) -> httpx.Response:
        if str(request.url).endswith("/api/v1/source/verify"):
            return httpx.Response(200, json={"ok": False, "data": {
                "category": "download", "message": "下载失败: 404",
            }})
        return httpx.Response(200, json={"ok": True})

    _mock_http(handler)
    before = env_file.read_text(encoding="utf-8")
    with TestClient(webui.app) as client:
        r = client.put("/api/config", json={"values": {
            "FNMUSIC_NETEASE_ENABLED": "false",
            "FNMUSIC_LX_ENABLED": "true",
            "LX_SOURCE_URL": "https://bad/1.js",
        }})
        assert r.status_code == 400
        assert "校验未通过" in r.json()["error"]
    assert env_file.read_text(encoding="utf-8") == before  # 校验失败不落盘


# ------------------------------------------------------------------ status / platforms ---

def test_supervisor_status_parses_despite_nonzero_exit(monkeypatch):
    """按需加载下 status 必有 STOPPED 程序，supervisorctl 退出码 3 是常态而非失败。"""
    monkeypatch.setattr(webui, "supervisorctl", lambda *a, timeout=20.0: (3, (
        "musicdl                        STOPPED   Not started\n"
        "musicbox                       RUNNING   pid 7, uptime 0:01:00\n"
        "lxmusic                        FATAL     Exited too quickly"
    )))
    st = webui.supervisor_status()
    assert st["musicdl"]["state"] == "STOPPED"
    assert st["musicbox"]["state"] == "RUNNING"
    assert st["lxmusic"]["state"] == "FATAL"


def test_supervisor_status_connection_error_returns_empty(monkeypatch):
    monkeypatch.setattr(webui, "supervisorctl",
                        lambda *a, timeout=20.0: (1, "error: <class 'ConnectionRefusedError'>, [Errno 111]"))
    assert webui.supervisor_status() == {}


def test_status_aggregates_processes_and_health(env_file, svctl, monkeypatch):
    monkeypatch.setitem(webui.CONF, "musicdl_url", "http://md.test")
    monkeypatch.setitem(webui.CONF, "musicbox_url", "http://mb.test")
    monkeypatch.setitem(webui.CONF, "lx_url", "http://lx.test")

    def handler(request: httpx.Request) -> httpx.Response:
        host = request.url.host
        if host == "mb.test":
            return httpx.Response(200, json={"ok": True, "service": "musicbox"})
        if host == "lx.test":
            return httpx.Response(200, json={"ok": True, "data": {
                "configured": True, "url": "https://s/1.js", "initialized": True,
                "last_error": "", "source": {"name": "t", "running": True, "platforms": {"kw": {}}},
            }})
        return httpx.Response(500)

    _mock_http(handler)
    # 当前 provider 是 musicbox（BASE_ENV）
    with TestClient(webui.app) as client:
        r = client.get("/api/status")
        assert r.status_code == 200
        rj = r.json()
        assert rj["version"] == "2.0.0"
        assert rj["current_provider"] == "musicbox"
        assert rj["processes"]["musicbox"]["state"] == "RUNNING"
        assert rj["processes"]["lxmusic"]["state"] == "STOPPED"
        assert rj["services"]["musicbox"]["reachable"] is True
        assert rj["services"]["lxmusic"]["note"]  # 未启用提示
        assert rj["lx_source"] is None


def test_platforms_from_musicdl(env_file, monkeypatch):
    monkeypatch.setitem(webui.CONF, "musicdl_url", "http://md.test")
    _mock_http(lambda r: httpx.Response(200, json={
        "enabled": ["KuwoMusicClient"], "registered": ["BaiduMusicClient", "KuwoMusicClient"],
    }))
    with TestClient(webui.app) as client:
        r = client.get("/api/platforms")
        assert r.status_code == 200
        rj = r.json()
        assert rj["enabled"] == ["KuwoMusicClient"]
        assert "BaiduMusicClient" in rj["registered"]


def test_platforms_unreachable_503(env_file):
    def handler(request):
        return httpx.Response(502)

    _mock_http(handler)
    with TestClient(webui.app) as client:
        r = client.get("/api/platforms")
        assert r.status_code == 503
        assert "hint" in r.json()


# ------------------------------------------------------------------ 网易反代/二维码 ---

def test_netease_auth_proxy_passthrough(env_file, monkeypatch):
    monkeypatch.setitem(webui.CONF, "musicbox_url", "http://mb.test")
    hits = {}

    def handler(request: httpx.Request) -> httpx.Response:
        path = request.url.path
        hits[path] = dict(request.url.params)
        if path == "/api/v1/auth/login":
            return httpx.Response(200, json={"code": 200, "unikey": "KEY1"})
        if path == "/api/v1/auth/login/check":
            return httpx.Response(200, json={"code": 801})
        return httpx.Response(404)

    _mock_http(handler)
    with TestClient(webui.app) as client:
        r = client.post("/api/netease/auth/login")
        assert r.status_code == 200 and r.json()["unikey"] == "KEY1"
        r2 = client.get("/api/netease/auth/login/check", params={"unikey": "KEY1"})
        assert r2.status_code == 200 and r2.json()["code"] == 801
        assert hits["/api/v1/auth/login/check"]["unikey"] == "KEY1"  # 查询串透传
        r3 = client.get("/api/netease/auth/evil")
        assert r3.status_code == 404  # 白名单外


def test_netease_qr_svg(env_file):
    qrcode = pytest.importorskip("qrcode")
    with TestClient(webui.app) as client:
        r = client.get("/api/netease/qr", params={"unikey": "KEY1"})
        assert r.status_code == 200
        assert r.headers["content-type"].startswith("image/svg+xml")
        assert b"svg" in r.content
        assert client.get("/api/netease/qr").status_code == 422  # 缺 unikey


# ------------------------------------------------------------------ 静态首页 ---

def test_index_served():
    with TestClient(webui.app) as client:
        r = client.get("/")
        assert r.status_code == 200
        assert "fnmusic-ext" in r.text
        assert "text/html" in r.headers["content-type"]
